/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpakovkaProektaRouteImport } from './routes/upakovka-proekta'
import { Route as TelegramBotyDlyaBiznesaRouteImport } from './routes/telegram-boty-dlya-biznesa'
import { Route as SaytyDlyaBiznesaRouteImport } from './routes/sayty-dlya-biznesa'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IiAssistentDlyaBiznesaRouteImport } from './routes/ii-assistent-dlya-biznesa'
import { Route as CaseSaytGostevyeDomikiRouteImport } from './routes/case-sayt-gostevye-domiki'
import { Route as CaseCifrovoyAvatarRouteImport } from './routes/case-cifrovoy-avatar'
import { Route as CaseB2bHorecaRouteImport } from './routes/case-b2b-horeca'
import { Route as CaseAiTelegramBotRouteImport } from './routes/case-ai-telegram-bot'
import { Route as AvtomatizaciyaBiznesaAiRouteImport } from './routes/avtomatizaciya-biznesa-ai'
import { Route as AiVideoDlyaBiznesaRouteImport } from './routes/ai-video-dlya-biznesa'
import { Route as IndexRouteImport } from './routes/index'

const UpakovkaProektaRoute = UpakovkaProektaRouteImport.update({
  id: '/upakovka-proekta',
  path: '/upakovka-proekta',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramBotyDlyaBiznesaRoute = TelegramBotyDlyaBiznesaRouteImport.update({
  id: '/telegram-boty-dlya-biznesa',
  path: '/telegram-boty-dlya-biznesa',
  getParentRoute: () => rootRouteImport,
} as any)
const SaytyDlyaBiznesaRoute = SaytyDlyaBiznesaRouteImport.update({
  id: '/sayty-dlya-biznesa',
  path: '/sayty-dlya-biznesa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IiAssistentDlyaBiznesaRoute = IiAssistentDlyaBiznesaRouteImport.update({
  id: '/ii-assistent-dlya-biznesa',
  path: '/ii-assistent-dlya-biznesa',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseSaytGostevyeDomikiRoute = CaseSaytGostevyeDomikiRouteImport.update({
  id: '/case-sayt-gostevye-domiki',
  path: '/case-sayt-gostevye-domiki',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCifrovoyAvatarRoute = CaseCifrovoyAvatarRouteImport.update({
  id: '/case-cifrovoy-avatar',
  path: '/case-cifrovoy-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseB2bHorecaRoute = CaseB2bHorecaRouteImport.update({
  id: '/case-b2b-horeca',
  path: '/case-b2b-horeca',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseAiTelegramBotRoute = CaseAiTelegramBotRouteImport.update({
  id: '/case-ai-telegram-bot',
  path: '/case-ai-telegram-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AvtomatizaciyaBiznesaAiRoute = AvtomatizaciyaBiznesaAiRouteImport.update({
  id: '/avtomatizaciya-biznesa-ai',
  path: '/avtomatizaciya-biznesa-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVideoDlyaBiznesaRoute = AiVideoDlyaBiznesaRouteImport.update({
  id: '/ai-video-dlya-biznesa',
  path: '/ai-video-dlya-biznesa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-video-dlya-biznesa': typeof AiVideoDlyaBiznesaRoute
  '/avtomatizaciya-biznesa-ai': typeof AvtomatizaciyaBiznesaAiRoute
  '/case-ai-telegram-bot': typeof CaseAiTelegramBotRoute
  '/case-b2b-horeca': typeof CaseB2bHorecaRoute
  '/case-cifrovoy-avatar': typeof CaseCifrovoyAvatarRoute
  '/case-sayt-gostevye-domiki': typeof CaseSaytGostevyeDomikiRoute
  '/ii-assistent-dlya-biznesa': typeof IiAssistentDlyaBiznesaRoute
  '/privacy': typeof PrivacyRoute
  '/sayty-dlya-biznesa': typeof SaytyDlyaBiznesaRoute
  '/telegram-boty-dlya-biznesa': typeof TelegramBotyDlyaBiznesaRoute
  '/upakovka-proekta': typeof UpakovkaProektaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-video-dlya-biznesa': typeof AiVideoDlyaBiznesaRoute
  '/avtomatizaciya-biznesa-ai': typeof AvtomatizaciyaBiznesaAiRoute
  '/case-ai-telegram-bot': typeof CaseAiTelegramBotRoute
  '/case-b2b-horeca': typeof CaseB2bHorecaRoute
  '/case-cifrovoy-avatar': typeof CaseCifrovoyAvatarRoute
  '/case-sayt-gostevye-domiki': typeof CaseSaytGostevyeDomikiRoute
  '/ii-assistent-dlya-biznesa': typeof IiAssistentDlyaBiznesaRoute
  '/privacy': typeof PrivacyRoute
  '/sayty-dlya-biznesa': typeof SaytyDlyaBiznesaRoute
  '/telegram-boty-dlya-biznesa': typeof TelegramBotyDlyaBiznesaRoute
  '/upakovka-proekta': typeof UpakovkaProektaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-video-dlya-biznesa': typeof AiVideoDlyaBiznesaRoute
  '/avtomatizaciya-biznesa-ai': typeof AvtomatizaciyaBiznesaAiRoute
  '/case-ai-telegram-bot': typeof CaseAiTelegramBotRoute
  '/case-b2b-horeca': typeof CaseB2bHorecaRoute
  '/case-cifrovoy-avatar': typeof CaseCifrovoyAvatarRoute
  '/case-sayt-gostevye-domiki': typeof CaseSaytGostevyeDomikiRoute
  '/ii-assistent-dlya-biznesa': typeof IiAssistentDlyaBiznesaRoute
  '/privacy': typeof PrivacyRoute
  '/sayty-dlya-biznesa': typeof SaytyDlyaBiznesaRoute
  '/telegram-boty-dlya-biznesa': typeof TelegramBotyDlyaBiznesaRoute
  '/upakovka-proekta': typeof UpakovkaProektaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-video-dlya-biznesa'
    | '/avtomatizaciya-biznesa-ai'
    | '/case-ai-telegram-bot'
    | '/case-b2b-horeca'
    | '/case-cifrovoy-avatar'
    | '/case-sayt-gostevye-domiki'
    | '/ii-assistent-dlya-biznesa'
    | '/privacy'
    | '/sayty-dlya-biznesa'
    | '/telegram-boty-dlya-biznesa'
    | '/upakovka-proekta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-video-dlya-biznesa'
    | '/avtomatizaciya-biznesa-ai'
    | '/case-ai-telegram-bot'
    | '/case-b2b-horeca'
    | '/case-cifrovoy-avatar'
    | '/case-sayt-gostevye-domiki'
    | '/ii-assistent-dlya-biznesa'
    | '/privacy'
    | '/sayty-dlya-biznesa'
    | '/telegram-boty-dlya-biznesa'
    | '/upakovka-proekta'
  id:
    | '__root__'
    | '/'
    | '/ai-video-dlya-biznesa'
    | '/avtomatizaciya-biznesa-ai'
    | '/case-ai-telegram-bot'
    | '/case-b2b-horeca'
    | '/case-cifrovoy-avatar'
    | '/case-sayt-gostevye-domiki'
    | '/ii-assistent-dlya-biznesa'
    | '/privacy'
    | '/sayty-dlya-biznesa'
    | '/telegram-boty-dlya-biznesa'
    | '/upakovka-proekta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiVideoDlyaBiznesaRoute: typeof AiVideoDlyaBiznesaRoute
  AvtomatizaciyaBiznesaAiRoute: typeof AvtomatizaciyaBiznesaAiRoute
  CaseAiTelegramBotRoute: typeof CaseAiTelegramBotRoute
  CaseB2bHorecaRoute: typeof CaseB2bHorecaRoute
  CaseCifrovoyAvatarRoute: typeof CaseCifrovoyAvatarRoute
  CaseSaytGostevyeDomikiRoute: typeof CaseSaytGostevyeDomikiRoute
  IiAssistentDlyaBiznesaRoute: typeof IiAssistentDlyaBiznesaRoute
  PrivacyRoute: typeof PrivacyRoute
  SaytyDlyaBiznesaRoute: typeof SaytyDlyaBiznesaRoute
  TelegramBotyDlyaBiznesaRoute: typeof TelegramBotyDlyaBiznesaRoute
  UpakovkaProektaRoute: typeof UpakovkaProektaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upakovka-proekta': {
      id: '/upakovka-proekta'
      path: '/upakovka-proekta'
      fullPath: '/upakovka-proekta'
      preLoaderRoute: typeof UpakovkaProektaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram-boty-dlya-biznesa': {
      id: '/telegram-boty-dlya-biznesa'
      path: '/telegram-boty-dlya-biznesa'
      fullPath: '/telegram-boty-dlya-biznesa'
      preLoaderRoute: typeof TelegramBotyDlyaBiznesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sayty-dlya-biznesa': {
      id: '/sayty-dlya-biznesa'
      path: '/sayty-dlya-biznesa'
      fullPath: '/sayty-dlya-biznesa'
      preLoaderRoute: typeof SaytyDlyaBiznesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ii-assistent-dlya-biznesa': {
      id: '/ii-assistent-dlya-biznesa'
      path: '/ii-assistent-dlya-biznesa'
      fullPath: '/ii-assistent-dlya-biznesa'
      preLoaderRoute: typeof IiAssistentDlyaBiznesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-sayt-gostevye-domiki': {
      id: '/case-sayt-gostevye-domiki'
      path: '/case-sayt-gostevye-domiki'
      fullPath: '/case-sayt-gostevye-domiki'
      preLoaderRoute: typeof CaseSaytGostevyeDomikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-cifrovoy-avatar': {
      id: '/case-cifrovoy-avatar'
      path: '/case-cifrovoy-avatar'
      fullPath: '/case-cifrovoy-avatar'
      preLoaderRoute: typeof CaseCifrovoyAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-b2b-horeca': {
      id: '/case-b2b-horeca'
      path: '/case-b2b-horeca'
      fullPath: '/case-b2b-horeca'
      preLoaderRoute: typeof CaseB2bHorecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-ai-telegram-bot': {
      id: '/case-ai-telegram-bot'
      path: '/case-ai-telegram-bot'
      fullPath: '/case-ai-telegram-bot'
      preLoaderRoute: typeof CaseAiTelegramBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avtomatizaciya-biznesa-ai': {
      id: '/avtomatizaciya-biznesa-ai'
      path: '/avtomatizaciya-biznesa-ai'
      fullPath: '/avtomatizaciya-biznesa-ai'
      preLoaderRoute: typeof AvtomatizaciyaBiznesaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-video-dlya-biznesa': {
      id: '/ai-video-dlya-biznesa'
      path: '/ai-video-dlya-biznesa'
      fullPath: '/ai-video-dlya-biznesa'
      preLoaderRoute: typeof AiVideoDlyaBiznesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiVideoDlyaBiznesaRoute: AiVideoDlyaBiznesaRoute,
  AvtomatizaciyaBiznesaAiRoute: AvtomatizaciyaBiznesaAiRoute,
  CaseAiTelegramBotRoute: CaseAiTelegramBotRoute,
  CaseB2bHorecaRoute: CaseB2bHorecaRoute,
  CaseCifrovoyAvatarRoute: CaseCifrovoyAvatarRoute,
  CaseSaytGostevyeDomikiRoute: CaseSaytGostevyeDomikiRoute,
  IiAssistentDlyaBiznesaRoute: IiAssistentDlyaBiznesaRoute,
  PrivacyRoute: PrivacyRoute,
  SaytyDlyaBiznesaRoute: SaytyDlyaBiznesaRoute,
  TelegramBotyDlyaBiznesaRoute: TelegramBotyDlyaBiznesaRoute,
  UpakovkaProektaRoute: UpakovkaProektaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
